indice1 =[
    "HNX30","HNXIndex","HNXUpcomIndex","VN100","VN30","VNALLSHARE","VNCOND","VNCONS","VNDIAMOND","VNENE",
    "VNFIN","VNFINLEAD"]
indice2 =[
    "VNFINSELECT","VNHEAL","VNIND","VNINDEX","VNIT","VNMAT","VNMIDCAP","VNREAL",
    "VNSI","VNSMALLCAP","VNUTI","VNX50","VNXALLSHARE"]